language: python
python:
#  - "2.4"
#  - "2.5"
#  - "2.6"
  - "2.7"
#  - "3.1"
#  - "3.2"
#  - "3.3"

# command to install dependencies
# install: "pip install -r requirements.txt --use-mirrors"

# command to run tests
script: python test_rpdb2.py

branches:
  only:
    - experiment_test
