language: python
python:
# - "2.5"    Python 2.5 no longer supported by Travis CI
  - "2.6"
  - "2.7"
#  - "3.1"   Python 3.1 no longer supported by Travic CI
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"  
  - "pypy"
#  - "pypy3" # Disabling pypy3 on Travis until bug is resolved.

matrix:
  allow_failures:
    - env: "pypy" # pypy not stable...



# command to install dependencies
# install: "pip install -r requirements.txt --use-mirrors"

# command to run tests
script: 
- python run_unit_tests.py
- python run_func_tests.py -v
